### ISSUE TITLE
Error: A constant constructor can't call a non-constant super constructor.

### ISSUE THREAD

**Issue by ompadmani71** [AppCheap/awesome_bottom_bar#10]
import 'package:flutter/material.dart';
import 'package:awesome_bottom_bar/awesome_bottom_bar.dart';

class Salomon extends StatefulWidget {
  static const String routeName = '/product';
  final List<TabItem> items;

  const Salomon({
    Key? key,
    required this.items,
  }) : super(key: key);

  @override
  _SalomonState createState() => _SalomonState();
}

class _SalomonState extends State<Salomon> {
  int visit = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          const SizedBox(height: 87),
          Container(),
          BottomBarSalomon(
            items: widget.items,
            color: Colors.blue,
            backgroundColor: Colors.white,
            colorSelected: Colors.white,
            backgroundSelected: Colors.blue,
            indexSelected: visit,
            animated: false,
            onTap: (index) => setState(() {
              visit = index;
            }),
          ),
        ],
      ),
      bottomNavigationBar: BottomBarSalomon(
        items: widget.items,
        color: Colors.blue,
        backgroundColor: Colors.red.withOpacity(0.4),
        colorSelected: Colors.white,
        backgroundSelected: Colors.blue,
        indexSelected: visit,
        onTap: (index) => setState(() {
          visit = index;
        }),
      ),
    );
  }
}

==========================================================
![image](https://github.com/AppCheap/awesome_bottom_bar/assets/108392662/1b273302-80fe-4f40-9037-7ed999733783)
==========================================================
![image](https://github.com/AppCheap/awesome_bottom_bar/assets/108392662/37f9ad65-f775-4deb-b14f-91bf320dfc12)

And if I remove the const from 'C:\Users\LENOVO\AppData\Local\Pub\Cache\hosted\pub.dev\awesome_bottom_bar-1.2.3\lib\widgets\inspired\stack.dart' then it's give me another error 

which is here
![image](https://github.com/AppCheap/awesome_bottom_bar/assets/108392662/d602c53d-c8cb-47b7-93d3-cc701eaf6959)

please give me a soluction for the same asap.

**Comment by Rimansh1464** [comment]
@ompadmani71  please add key in TabItem
Ex: 
  List<TabItem> items = [
    TabItem(
      key: 'home', // Assign a unique key
      icon: Icons.home,
      title: 'Home',
    ),
    TabItem(
      key: 'tools', // Assign a unique key
      icon: Icons.add_chart_outlined,
      title: 'Tools',
    ),
    TabItem(
      key: 'activity', // Assign a unique key
      icon: Icons.add_business_sharp,
      title: 'Activity',
    ),
  ];

**Comment by ompadmani71** [comment]
Thank you @Rimansh1464

**Comment by prince-appiah** [comment]
@Rimansh1464 I provided the key in my tab items but still got the error. Any other solution I could use?
